# Generated by Django 3.1.4 on 2020-12-29 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('side', models.CharField(choices=[('Paternal', 'Paternal'), ('Maternal', 'Maternal')], default='Maternal', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cousin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrandParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('side', models.CharField(choices=[('Paternal', 'Paternal'), ('Maternal', 'Maternal')], default='Maternal', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uncle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('side', models.CharField(choices=[('Paternal', 'Paternal'), ('Maternal', 'Maternal')], default='Maternal', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('aunt', models.ManyToManyField(to='api.Aunt')),
                ('cousin', models.ManyToManyField(to='api.Cousin')),
                ('grandparents', models.ManyToManyField(to='api.GrandParent')),
                ('uncle', models.ManyToManyField(to='api.Uncle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
