# Generated by Django 3.1.4 on 2020-12-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aunt',
            name='spouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cousin',
            name='spouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uncle',
            name='spouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
