# Generated by Django 3.1.4 on 2020-12-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201229_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cousin',
            name='Father',
        ),
        migrations.AddField(
            model_name='cousin',
            name='Father',
            field=models.ManyToManyField(blank=True, null=True, to='api.Uncle'),
        ),
        migrations.RemoveField(
            model_name='cousin',
            name='Mother',
        ),
        migrations.AddField(
            model_name='cousin',
            name='Mother',
            field=models.ManyToManyField(blank=True, null=True, to='api.Aunt'),
        ),
    ]
