# Generated by Django 3.1.4 on 2020-12-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201229_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cousin',
            name='Father',
        ),
        migrations.AddField(
            model_name='cousin',
            name='Father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.uncle'),
        ),
        migrations.RemoveField(
            model_name='cousin',
            name='Mother',
        ),
        migrations.AddField(
            model_name='cousin',
            name='Mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aunt'),
        ),
    ]
