# Generated by Django 3.1.4 on 2020-12-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201229_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandparent',
            name='GType',
            field=models.CharField(choices=[('Great', 'Great'), ('Regular', 'Regular')], default='Regular', max_length=15),
        ),
    ]
