# Generated by Django 3.1.4 on 2020-12-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201230_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familytree',
            old_name='aunt',
            new_name='aunts',
        ),
        migrations.RenameField(
            model_name='familytree',
            old_name='cousin',
            new_name='cousins',
        ),
        migrations.RenameField(
            model_name='familytree',
            old_name='uncle',
            new_name='uncles',
        ),
    ]
