# Generated by Django 3.1.4 on 2021-01-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210103_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familytree',
            old_name='sibling',
            new_name='siblings',
        ),
    ]
