# Generated by Django 3.1.4 on 2021-01-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210103_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grandparent',
            name='GType',
        ),
    ]
