# Generated by Django 3.1.4 on 2021-01-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210111_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familytree',
            name='aunts',
        ),
        migrations.RemoveField(
            model_name='familytree',
            name='cousins',
        ),
        migrations.RemoveField(
            model_name='familytree',
            name='grandparents',
        ),
        migrations.RemoveField(
            model_name='familytree',
            name='siblings',
        ),
        migrations.RemoveField(
            model_name='familytree',
            name='uncles',
        ),
    ]
