# Generated by Django 3.1.4 on 2021-01-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210119_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cousin',
            name='Father',
        ),
        migrations.RemoveField(
            model_name='cousin',
            name='Mother',
        ),
        migrations.RemoveField(
            model_name='cousin',
            name='spouse',
        ),
        migrations.AddField(
            model_name='cousin',
            name='side',
            field=models.CharField(choices=[('Paternal', 'Paternal'), ('Maternal', 'Maternal')], default='Maternal', max_length=10),
        ),
    ]
